### ISSUE TITLE
Question: High TTFB when using Quicklinks?

### ISSUE THREAD

**Issue by david-wg2** [GoogleChromeLabs/quicklink#159] opened 2020-02-07 13:46 UTC
Hi. I'm looking at the demo site (https://anton-karlovskiy-quicklink-news.glitch.me/pages/contact.html), and I'm seeing very high TTFB: 
![Screenshot 2020-02-07 at 14 41 34](https://user-images.githubusercontent.com/36410074/74034176-0d0d3180-49b8-11ea-9960-1ccd32303913.png)

I was hoping this would be around 0 with Quicklinks, why isn't that the case?

**Comment by demianrenzulli** [comment] 2020-02-08 16:46
Hi @david-wg2! Thanks for your question.

Quicklink prefetches in-viewport links, so the impact of the library can be perceived when navigating from one page to another, by clicking on a link inside that page.

I have the feeling that what you did was opening [contact.html](https://anton-karlovskiy-quicklink-news.glitch.me/pages/contact.html) directly (not navigating), is that correct?

In that case, unless the page is already in the cache (for example, because you visited it before), it will have to be retrieved from the network, which explains why you are observing a high TTFB value.

A better would be:

1. Opening the [home page](https://anton-karlovskiy-quicklink-news.glitch.me/).
2. Clicking on a link in the viewport.
3. Checking the time it takes for the page to be retrieved, by inspecting the Network tab.

If you want to explore more techniques to measure the impact of the library you can check the [impact measurement guide](https://getquick.link/measure/).

Let us know if it's more clear now!

**Comment by tipsy** [comment] 2020-02-08 17:26
Hi @demianrenzulli, thanks for getting back to me so quickly.

> I have the feeling that what you did was opening contact.html directly (not navigating), is that correct?

No, this was when clicking the actual anchor tags in the menu, but I realize now that it was because I had disabled my browser cache.

The server in the project I'm trying to use quicklinks for sets `Cache-Control: no-cache, no-store, must-revalidate`, which I guess explains why it didn't work there either. I guess there isn't too much I can do in that scenario? 🤔

**Comment by demianrenzulli** [comment] 2020-02-08 20:21
Thanks for sharing those details @david-wg2!

From the list of headers you've shared, I think the one that will invalidate prefetching is `no-store`. In our  tests, `no-cache` didn't prevent the resource from being stored in the prefetch cache (we have summarized the different variations of caching headers [in this issue](https://github.com/GoogleChromeLabs/quicklink/issues/140).

With that said, the first recommendation would be to relax the HTTP caching header policy you have in your backend for those resources. If that's not possible, there's something else you can do:

[This version](https://anton-karlovskiy-quicklink-news-workbox.glitch.me/) of the demo you've shared, combines prefetching with a service worker, using a workbox runtime strategy to extend the lifetime of the prefetch resource :[workbox.strategies.staleWhileRevalidate()](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#stale-while-revalidate).

Implementing such a strategy would allow you to prefetch the resource with quicklink, and store it in the SW cache using Workbox, instead of relying on browser caching.

There are different ways of achieving prefetching with SW. The one I mentioned before is compatible with Quicklink, and it's recommended. If you are curious and want to know more, we've just released [a guide](https://dev.to/drenzulli/prefetching-techniques-with-workbox-3bpc) summarizing them.

Does this help?

**Comment by johanjanssens** [comment] 2020-02-08 20:54
@demianrenzulli @david-wg2  Just for completeness. 

According to the [RFC7234](https://tools.ietf.org/html/rfc7234#section-5.2.2.2) and in the context of browser caching `no-cache`means: 

> The "no-cache" response directive indicates that the response MUST
>    NOT be used to satisfy a subsequent request without successful
>    validation on the origin server.  This allows an origin server to
>    prevent a cache from using it to satisfy a request without contacting
>    it, even by caches that have been configured to send stale responses.

This means that the browser can cache the response but needs to re-contact the origin to validate it. If the resource is valid the origin should respond with a `304 Not Modified` and the browser will use the cached resource, if not the browser will request a new resource representation from the origin.

I have not been able to confirm the 5min you mentioned in #140 I have been able to confirm that ones prefetched normal browser caching behavior applies.

While slightly outdates, following can also be useful in terms of caching behavior and cache control headers in other browsers: https://www.mnot.net/blog/2017/03/16/browser-caching

**Comment by demianrenzulli** [comment] 2020-02-08 21:10
This is great @johanjanssens! Thanks a lot for sharing these additional details.

Regarding `no-cache`, it seems we fell short in our tests. Thanks for going the extra mile on this point. It would be interesting to put together a test to confirm this in practice, but I believe what you've shared should be how most browsers have implemented it.

Regarding the 5 minutes: we got confirmation that this is the case for Chrome, but it's not clear which window other supporting browsers might have implemented (this wasn't clear in the docs either). Recall that after the 5 minutes, the resource's `cache-control` headers should apply. 
In the cases where quicklink uses `fetch()` as fallback ([browsers that don't support prefetch](https://caniuse.com/#search=prefetch)) you should only rely on the caching headers of the resource (without counting on those extra 5 minutes). This means that, if the resource has `cache-control: max-age=0`, you'll see no benefits on those browsers (unless you use service workers).

I think we need to do a better work on documenting which role HTTP headers play with prefetch technniques, in general, but these updates should be good for developers to make a decision around it.

@david-wg2 wondering if these clarifications help.
@johanjanssens thanks again for jumping in!

**Comment by johanjanssens** [comment] 2020-02-08 21:32
@demianrenzulli  You are most welcome.

- `no-cache` I can confirm this in my own tests, this cache-control header if often mis-understood, I have seen a lot of developers who believe it means **do not cache** which is not the case.

- regarding `5min` thanks for confirming that. 

Regarding `cache-control: max-age=0` added  'stale-while-revalidate', as defined [RFC5861](in https://tools.ietf.org/html/rfc5861) can serve as a lazy refresh. The resource will be validated async while it's being served from cache. Some [CDN's](https://www.fastly.com/blog/stale-while-revalidate-stale-if-error-available-today) have also started to support this.

**Comment by tipsy** [comment] 2020-02-08 22:13
> @david-wg2 wondering if these clarifications help.

Yes, both you and @johanjanssens have provided excellent information for understanding the issue.

I thought I had solved my problem by changing my header to `Cache-Control: max-age=60`, but if the prefetch-cache adds 5 minutes, then that's a bit too much. I'll guess I'll have to have a closer look at how it's best solve this

> In the cases where quicklink uses fetch() as fallback (browsers that don't support prefetch) you should only rely on the caching headers of the resource (without counting on those extra 5 minutes).

Is it possible to instruct quicklink to just use fetch rather than prefetch? That sounds like an easy solution to my current issues (5 minutes being too long).

> Regarding cache-control: max-age=0 added stale-while-revalidate, as defined [RFC5861](in https://tools.ietf.org/html/rfc5861) can serve as a lazy refresh. The resource will be validated async while it's being served from cache. Some CDN's have also started to support this, which in some scenario's prevents the need for a service worker approach.

That sounds interesting, I'll have to look into that too.

**Comment by tipsy** [comment] 2020-02-08 22:58
> Is it possible to instruct quicklink to just use fetch rather than prefetch? That sounds like an easy solution to my current issues (5 minutes being too long).

`quicklink.listen({priority: true}))` combined with a short max-age seems to work well for me !

**Comment by demianrenzulli** [comment] 2020-02-08 23:25
Hi @tipsy! Glad the priority option ended up working for you. Seems like that strategy should work across browsers as well.

I guess we can just close this one right now, but feel free to re-open if you find any issues with this approach or have any additional feedback 👍

**Closed by demianrenzulli** 2020-02-08 23:25 UTC

**Comment by tipsy** [comment] 2020-02-08 23:27
Yes, thank you for your help!

**Comment by tipsy** [comment] 2020-02-09 10:09
For people who might be interested, I played around a bit more with this and came up with the following hack, based on the idea of `stale-while-revalidate` idea (which I couldn't get to work). I went back to prefetch, set my cache to seven days, and added a cache breaker to my layout template:

```js
Promise.all([ // cache breaker
    axios.get(location.origin + location.pathname + location.search), // the URL below also adds a unique query param
    axios.get(location.origin + location.pathname + location.search + (location.search === "" ? '?' : '&') + `cache_ts=${new Date().getTime()}`)
]).then(([cached, fresh]) => {
    if (cached.data !== fresh.data) location.reload();
});
```

Not sure if this is a terrible idea yet, will update if it blows up.

For context, my usecase is a server-side rendered app which is slow, requires authentication, and very rarely changes content.
