### ISSUE TITLE
Uncaught (in promise) 

### ISSUE THREAD

**Issue by MatTeague** [GoogleChromeLabs/quicklink#59] opened 2018-12-18 17:33 UTC
Hi,

I've included the umd version of quicklinks but I keep getting several console errors repeating the error:

```
Uncaught (in promise) Event {isTrusted: true, type: "error", target: link, currentTarget: null, eventPhase: 0, …}bubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: nulldefaultPrevented: falseeventPhase: 0isTrusted: truepath: (5) [link, head, html.js.no-focus-outline.sizes.customelements.history.pointerevents.postmessage.webgl.websockets.css…, document, Window]returnValue: truesrcElement: linktarget: linktimeStamp: 2088.500000001659type: "error"__proto__: Event
Promise.then (async)
r @ quicklink.umd.js:1
c @ quicklink.umd.js:1
(anonymous) @ quicklink.umd.js:1
(anonymous) @ quicklink.umd.js:1
```

Any advice with resolving these errors would be great. Thanks.

**Comment by addyosmani** [comment] 2018-12-18 18:09
Could you share more details about your testing setup so we can try reproducing the error? (e.g browser, any configuration options passed, minimal test case). Cheers!

**Comment by lukeed** [comment] 2018-12-18 20:10
Looks like the `linkPrefetchStrategy` method was used, which likely means that the `link.onerror` triggered. Maybe we should include a simple logger on `catch()` here? https://github.com/GoogleChromeLabs/quicklink/blob/master/src/prefetch.mjs#L109

Functionally, it wouldn't be very helpful, but it's a shot at debugging.

Or we can expose an option for user-derived error handler

**Comment by lukeed** [comment] 2018-12-19 18:56
Hey @MatTeague, It looks like that original error you reported is throwing because `/contact-us` does not exist. Because of this line (https://github.com/GoogleChromeLabs/quicklink/blob/master/src/prefetch.mjs#L44), any non-OK responses will just emit upwards, which is why an `Event` instance is logged to the console.

As for your latest report, `quicklink` won't be defined because your script tag has a `defer` attribute on it:

```html
<script src="/assets/js/quicklink.umd.js" defer></script>
```

This will execute the `<script id="quicklink">` block first, since it's not (and can't) be deferred. The `load` and `DOMContentLoaded` events fire after all script sources (deferred or not) are ready.

**Comment by tutuzhangdeqingtian** [comment] 2018-12-20 11:47
Hello @MatTeague ,have you solve the original error? What do you do to solve it? I meet the same error. I want to learn from you about resolving this error.

**Comment by MatTeague** [comment] 2018-12-20 21:15
Hi @lukeed thanks for the reply. I tried commenting out the link on the homepage which took you to the contact us page and removed the defer from the quicklink.umd.js file. However it didn't fix the issue and is still displaying.

**Comment by MatTeague** [comment] 2018-12-20 21:16
Hi @tutuzhangdeqingtian I'm afraid I'm still getting the issue and haven't been able to resolve it. Will post here once I have though

**Comment by tutuzhangdeqingtian** [comment] 2018-12-21 03:09
Hello @MatTeague Thanks for answering my qustion.

**Comment by randyou** [comment] 2018-12-24 07:05
use with [core-js](https://github.com/zloirock/core-js)  get Uncaught  promise reject in Firefox

**Comment by demianrenzulli** [comment] 2019-11-23 22:27
Hey @MatTeague, this issue has been opened for a year now.

Proceeding to close it, but feel free to reopen it if you still need help.

**Closed by demianrenzulli** 2019-11-23 22:27 UTC
Labels: question
