### ISSUE TITLE
Prefetching Cross Origin HTML Succeeds in Chrome 68, but fails in Chrome 75 because of CORB

### ISSUE THREAD

**Issue by elvinn** [GoogleChromeLabs/quicklink#101] opened 2019-06-26 06:55 UTC
Hi, I'm using `quick link` in https://zuizhi.ke.qq.com, and it works well in Chrome 68. However, prefetching cross origin HTML fails in Chrome 75 because of  [CORB](https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md#cross_origin-read-blocking-corb).

Here are details.  Using `quick link`, https://zuizhi.ke.qq.com will prefetch three html links like https://ke.qq.com/course/368477?quicklink=1. Also, the server sets header as `Access-Control-Allow-Origin: 'https://zuizhi.ke.qq.com'` and `Access-Control-Allow-Credentials: true`, So there is no problem about CORS. But according to  [CORB](https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md#cross_origin-read-blocking-corb), when response `Content-Type` is `text/html` and it is cross origin, the request is blocked.

I find that `quick link` adds `<link rel="prefetch" href="https://ke.qq.com/course/368477?quicklink=1">` in HTML to prefetch, and it fails in Chrome 75.
I also find that if I add `<link rel="prefetch" href="https://ke.qq.com/course/368477?quicklink=1" crossorigin>` in HTML manually, Chrome will not block these requests.

So can we use a config to add attribute `crossorigin` when  [create prefetch link](https://github.com/GoogleChromeLabs/quicklink/blob/master/src/prefetch.mjs#L39) or is there any other solution?

Thanks a lot.

**Comment by demianrenzulli** [comment] 2019-11-26 19:00
Hi @elvinn, 

I put together [this site](https://quicklink-3rd-party.glitch.me/), which contains `quicklink`, with `origins: true`, and hast three in-viewport links: the first two are cross-origin (the 2nd one for a subdomain), and the 3rd link for a same-origin url.

I tested this in the [latest stable versions](https://chromereleases.googleblog.com/) for desktop and mobile (Chrome 78). 

In all cases, links are prefetched correctly, and picked up from the prefetch cache. I'm not seeing any of these requests being blocked, which seems to be the expected behavior.

Since this issue has been open for a few months now, I'm closing it, but if you have any additional details to share, feel free to reopen it.

Cheers.

**Closed by demianrenzulli** 2019-11-26 19:00 UTC

**Comment by addyosmani** [comment] 2019-11-27 02:37
I wanted to add one additional future-facing note here. Browsers are shifting to a double-keyed cache that will have an impact on features like `<link rel=prefetch>` functioning cross-origin. This is in large part due to a desire to lock down fingerprinting/security vectors. While I don't believe the Chrome 75 issue you experienced was directly related, I do want to note that in future versions of Chrome, libraries like Quicklink are likely to be limited to fetching resources on same-origin only.

https://www.chromestatus.com/feature/5280299309072384

**Comment by demianrenzulli** [comment] 2019-11-27 02:49
Thanks @addyosmani!

BTW: Similar behavior was reported in #128, but in Safari. In that case, tests also seemed to suggest that `quicklink` was working as expected, but I guess, we can expect a similar behavior in the future.
